# Generated by Django 2.0.6 on 2018-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_privatebookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='private',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
