# Generated by Django 2.0.6 on 2018-06-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_bookmark_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='private',
        ),
    ]
